apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: insights-app-cjis
objects:
- apiVersion: cloud.redhat.com/v1alpha1
  kind: ClowdApp
  metadata:
    name: ${CLOWDAPP_NAME}
  spec:
    envName: ${ENV_NAME}
    dependencies:
      - ${DEPENDENT_APP_NAME}
    jobs:
    - name: "replication-runner"
      restartPolicy: Never
      podSpec:
        image: ${IMAGE_NAME}:${IMAGE_TAG}
        args: ["./replication_subscriber/runner.py"]
        env:
          - name: LOG_LEVEL
            value: ${LOG_LEVEL}
          - name: DB_SSL_MODE
            value: ${DB_SSL_MODE}
          - name: CLOWDER_ENABLED
            value: "true"
          - name: HBI_PUBLICATION
            value: ${HBI_PUBLICATION}
          - name: HBI_SUBSCRIPTION
            value: ${HBI_SUBSCRIPTION}
          - name: ALTER_SUBSCRIPTION
            value: ${ALTER_SUBSCRIPTION}
          - name: DROP_SUBSCRIPTION
            value: ${DROP_SUBSCRIPTION}
        resources:
          limits:
            cpu: ${CPU_LIMIT_REPLICATION_SUBSCRIPTOR}
            memory: ${MEMORY_LIMIT_REPLICATION_SUBSCRIPTOR}
          requests:
            cpu: ${CPU_REQUEST_REPLICATION_SUBSCRIPTOR}
            memory: ${MEMORY_REQUEST_REPLICATION_SUBSCRIPTOR}
        volumeMounts:
          - mountPath: /etc/db/hbi
            name: host-inventory-db
            readOnly: true
          - mountPath: /etc/db/rdsclientca
            name: rds-client-ca
            readOnly: true
        volumes:
          - name: host-inventory-db
            secret:
              items:
              - key: db.host
                path: db_host
              - key: db.name
                path: db_name
              - key: db.password
                path: db_password
              - key: db.port
                path: db_port
              - key: db.user
                path: db_user
              secretName: ${HBI_DB_SECRET}
              optional: true
          - name: rds-client-ca
            secret:
              items:
              - key: rds-cacert
                path: rds_cacert
              secretName: rds-client-ca
              optional: true
    database:
      sharedDbAppName: ${DB_NAME}
- apiVersion: cloud.redhat.com/v1alpha1
  kind: ClowdJobInvocation
  metadata:
    name: sample-replication-${REPLICATION_SUBSCRIPTION_RUN_NUMBER}
  spec:
    appName: ${CLOWDAPP_NAME}
    jobs:
      - replication-runner


parameters:
- name: REPLICATION_SUBSCRIPTION_RUN_NUMBER
  value: '1'
- name: LOG_LEVEL
  value: INFO
- name: CPU_REQUEST_REPLICATION_SUBSCRIPTOR
  value: 250m
- name: CPU_LIMIT_REPLICATION_SUBSCRIPTOR
  value: 500m
- name: MEMORY_REQUEST_REPLICATION_SUBSCRIPTOR
  value: 256Mi
- name: MEMORY_LIMIT_REPLICATION_SUBSCRIPTOR
  value: 512Mi
- description: Image tag
  name: IMAGE_TAG
  required: true
  value: latest
- description: Image NAME
  name: IMAGE_NAME
  required: true
  value: quay.io/chambrid/replication_subscriber
- description : ClowdEnvironment name
  name: ENV_NAME
  value: stage
- description: ClowdApp name
  name: CLOWDAPP_NAME
  value: sample-relicator
- name: DB_SSL_MODE
  value: prefer
- name: DB_NAME
  required: true
- name: DEPENDENT_APP_NAME
  required: true
- name: HBI_DB_SECRET
  value: host-inventory-db
- name: HBI_PUBLICATION
  value: hbi_hosts_pub_v1_0_0
- name: HBI_SUBSCRIPTION
  required: true
- name: ALTER_SUBSCRIPTION
  value: ''
- name: DROP_SUBSCRIPTION
  value: ''
